In [12]:
f = open("NM_207618.fasta", "r")
seq = f.readline()
seq

'>NM_207618.2 Mus musculus vomeronasal 1 receptor, D18 (V1rd18), mRNA\n'

In [12]:
with open("NM_207618.fasta", "r") as DNA:
    data = DNA.read().splitlines(True)
with open('1115dna.txt', 'w') as output:
    output.writelines(data[1:]) #첫번째 줄 제외 
f = open("1115dna.txt", "r")
a = f.read().replace('\n','')

def convert(seq):
    # 아미노산 시퀀스 변환 
    genetic_code = {
        'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
        'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
        'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
        'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
        'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
        'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
        'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
        'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
        'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
        'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
        'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
        'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
        'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
        'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
        'TAC':'Y', 'TAT':'Y', 'TAA':'_', 'TAG':'_',
        'TGC':'C', 'TGT':'C', 'TGA':'_', 'TGG':'W',
    }
    protein = ""
    if len(seq) % 3 == 0:
        for i in range(0, len(seq), 3):
            codon = seq[i: i+3]
            protein += genetic_code[codon]
    return protein
print(convert(a[20:938]))

MSTHDTSLKTTEEVAFQIILLCQFGVGTFANVFLFVYNFSPISTGSKQRPRQVILRHMAVANALTLFLTIFPNNMMTFAPIIPQTDLKCKLEFFTRLVARSTNLCSTCVLSIHQFVTLVPVNSGKGILRASVTNMASYSCYSCWFFSVLNNIYIPIKVTGPQLTDNNNNSKSKLFCSTSDFSVGIVFLRFAHDATFMSIMVWTSVSMVLLLHRHCQRMQYIFTLNQDPRGQAETTATHTILMLVVTFVGFYLLSLICIIFYTYFIYSHHSLRHCNDILVSGFPTISPLLLTFRDPKGPCSVFFNC_


In [14]:
import numpy as np 
x = np.array([1,3,5])
print(x.mean())
print(x.shape)


3.0
(3,)


In [17]:
import numpy as np 
a = np.array([[1,2,3], [2,3,4]])  #[], [] 을 [] 로 한 번 더 감싸야함
print(a.shape)

(2, 3)


In [18]:
x = np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [21]:
y = np.zeros([3,4])
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
import numpy as np 
list = ([[1,11], [2,12], [3,13]])
np_ary = np.array(list)
print(np_ary[:,1]) #import numpy as np 


[ 2 12]


In [25]:
import math 
math.sqrt(2)

1.4142135623730951

In [26]:
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [31]:
import numpy as np 
a = np.arange(15)
print(a)

b = a.reshape(3,5) #⬇️➡️ 요 순서다
print(b)

print(b[1][1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
6


In [35]:
import numpy as np 
zero_vector = np.zeros(3)
zero_vector #array([0., 0., 0.])

array([0., 0., 0.])

In [36]:
zero_matrix = np.zeros((4,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
x = np.array([1,2,3])
y = np.array([100,1000,10000])
z = x + y
z

array([  101,  1002, 10003])

In [38]:
x = np.array([1,2,3])
y = x + 1
y #array([2, 3, 4])

array([2, 3, 4])

In [39]:
x = np.array([4,8,12])
y = np.array([2,4,6])
z = x // y 
z

array([2, 2, 2], dtype=int32)

In [44]:
a = np.array([10,20,30,40,50,60,70,80,90])
print(a[1::2])

[20 40 60 80]


In [45]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = a > 50
print(b) #[False False False False False  True  True  True  True]


[False False False False False  True  True  True  True]


In [49]:
np.linspace(0,12,4) # array([ 0.,  4.,  8., 12.])
np.linspace(0,12,4, retstep=True) # (array([ 0.,  4.,  8., 12.]), 4.0)
#retstep(return step)이 참이면 샘플 간의 간격을 마지막 값으로 출력함

np.linspace(0,12,3,endpoint=False) #array([0., 4., 8.]) 마지막 값 생략



array([200.71743249, 168.63154528, 141.67477986, 119.02721532,
       100.        ])