In [20]:
import numpy as np # 모듈 가져오기
x = np.array([1,3,5]) #파이썬의 데이터형을 Numpy 형식으로 변환 
print(x.mean()) #평균 기능 수행 

print(x.shape) #shape는 해당 클래스에서 제공해주는 어트리뷰트이다. 1차원 배열로 3개의 원소가 있다는 결과가 나온다. 

# 2차원 배열을 만들어보자 
x = np.array([[1,3,5],[2,4,6]]) #2개의 원소를 가지고 있으며, 이들은 각각 3개의 원소를 가지고 있다. []로 한 번 더 감싸야 해!
print(x.shape)

x = np.array([1,3,5,2,4,6]).reshape(2,3) #reshape메소드를 추가하면 다음과 같이 Numpy의 2차원 배열을 원하는 모양으로 생성할 수 있다. 
print(x)

#Numphy형식의 2차원 배열을 1의 값들로 채우려면 다음과 같이 실행하면 된다'
y = np.ones([3,4])
print(y)

# 예제 
z = np.array([[1,3,5], [2,4,6]])
print("1번 index: ",x[1]) 
print("1번 index 평균:",x[1].mean())
print("전체 평균:",x.mean()) 
print(x.shape)

# quiz 
list1 = np.array([[1,3],[5, 2],[4,6]]) #2차원의 것을 Numpy 형식으로 변환 후 실행해주면 된다 (안하면 당연히 오류)
print(list1[1][1]) #index 1의 원소의 1번 원소
print(list1[:,1]) #모든 것(:)의 1번째 원소를 출력 [3 2 6]

# 루트 
print(type(np.sqrt)) #<class 'numpy.ufunc'>
print(np.sqrt([2,3,4])) #[1.41421356 1.73205081 2.        ] 자리는 미리 할당은 다 해놨다

3.0
(3,)
(2, 3)
[[1 3 5]
 [2 4 6]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1번 index:  [2 4 6]
1번 index 평균: 4.0
전체 평균: 3.5
(2, 3)
2
[3 2 6]
<class 'numpy.ufunc'>
[1.41421356 1.73205081 2.        ]


### 제로 벡터와 제로 행렬 


In [25]:
zero_matrix = np.zeros((5,3))
zero_matrix += 4 
#array([[4., 4., 4.],
       #[4., 4., 4.],
       #[4., 4., 4.],
       #[4., 4., 4.],
       #[4., 4., 4.]])
       
zero_matrix.reshape(3,5)
#array([[4., 4., 4., 4., 4.],
      # [4., 4., 4., 4., 4.],
      # [4., 4., 4., 4., 4.]])
      

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

### 전치 행렬
은 행과 열을 교환하여 얻어지는 행렬을 말하며 아래 그림과 같이 행렬의 값들을 주 대각선을 기준으로 위치를 바꾼 행렬을 의미한다

# 사칙연산?


In [35]:
x = np.array([1,3,5])
y = np.array([2,4,6])
print(x/y) #[0.5        0.75       0.83333333]

print(x+10) #[11 13 15]

x = np.array([[1,2,3], [4,5,6],[7,8,9]])
y = np.array([[4,4,100], [5,5,1000],[6,6,10000]])
print(x[:,1] + y[:,2]) #[  102  1005 10008]

# x = np.array([[1,2,3], [4,5,6], [7,8,9]])
# y = np.array([[4,4,100],[6,6,10000]])
# print(x[:,1] + y[:,2]) #ValueError        

x = np.array([21,13,35,32,4,6])
index = [1,3,5]
print(x[index]) #[13 32  6]

ary = np.random.random(5) #0과 1 사이의 무작위수 생성 
print(ary)
print(np.all(ary >= 0.3)) #False
print(np.any(ary >= 0.3)) #True



[0.5        0.75       0.83333333]
[11 13 15]
[  102  1005 10008]
[13 32  6]
[0.38334115 0.19098678 0.1919045  0.51126493 0.55135029]
False
True


## 등간격 나누기 
linspace()

In [38]:
np.linspace(0,12,4) #array([ 0.,  4.,  8., 12.])

np.linspace(0,12,4, retstep=True) #(array([ 0.,  4.,  8., 12.]), 4.0)  retstep=True: 샘플 간의 간격을 마지막 값으로 출력
np.linspace(0,12,3, endpoint=False) #array([0., 4., 8.])


array([0., 4., 8.])